### ISSUE TITLE
Orca Slicer not Work corretly

### ISSUE THREAD

**Issue by marcosvinirocha** [OrcaSlicer/OrcaSlicer#11434]
### Is there an existing issue for this problem?

- [x] I have searched the existing issues

### OrcaSlicer Version

2.3.1

### Operating System (OS)

Linux

### OS Version

Fedora 43

### Printer

Bambu lab a1 mini

### How to reproduce

1. open Orca slice on fedora 43 with other monitor
2. somentimes freeze ou not work.
3. If open in another monitor works 
4. if not has a monitor works 

### Actual results

Sometimes on Fedora 43, Orca Slicer doesn't open correctly. When I open it on another monitor it works normally, but sometimes when I open it with the laptop screen connected to a monitor it freezes and sometimes it doesn't work correctly at all.

### Expected results

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/fbc6ebb0-342f-40ff-8e54-31bb823c99cf" />

### Project file & Debug log uploads

not have

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Epickitrolaz** [comment]
I am having the same exact problem. I can reproduce it on versions V2.3.0 - V2.3.2 including alpha, beta and nightly releases. It sometimes just stops working when I import a 3d model, resize the window or alt+tab.

My system:
Archlinux x64_86
Gnome 49, wayland
AMD Ryzen 7 7800X3D
AMD Radeon RX 7900GRE

**Comment by haraldwer** [comment]
Same, also on fedora gnome 49, wayland, amd. I can't use orca because of this. In addition to what's described above, it sometimes also breaks when I slice a model or change a tab, or really anything that requires the layout to be recalculated or for a sub-window to be created. When this happens and I try to close the app, it shows me an "Do you want to save" modal, where I can press "Yes" to open the file manager, but then the file manager rendering is also frozen. I can still click "Cancel" though. Also, if I rotate the model while the 3d view is frozen and then alt-tab, sometimes the 3d view updates.

To me, it seems as if parts of the the rendering is frozen, even if the interactions still work. 

Let me know if you need help debugging!

**Comment by marwndev** [comment]
Same issue. On previous versions of Fedora I used to fix this by setting WEBKIT_DISABLE_COMPOSITING_MODE=1
It seems this is not working anymore.

**Comment by adiekwisch** [comment]
Same issue here. The last time I used Orca without a problem was before I upgraded from Fedora 42 to 43, so I have to assume it has something to do with the upgrade. 

The one graphics-related change I remember is that Mesa went from 25.1 to 25.2, maybe that is part of the issue.

**Comment by FifthZoner** [comment]
Hi!. I might have a solution for this issue. 

I'm using a fresh install of fedora 43 gnome and had roughly the same issues when using Orca with multiple monitors. When only one was on, things worked fine.
It seems the issues are fixed by upgrading mutter and mutter-common from 49.1-1 (I had it downgraded from 49.1.1-1 since it had a bug with workspace switching) to the newest version from testing repository: 49.2-2.

Both Orca 2.3.1 and a nightly build from a few days ago seem to be fixed by this update.

I used this command: 
```
sudo dnf update --enable-repo=updates-testing mutter
```

**Comment by daver360** [comment]
> I used this command:
> 
> ```
> sudo dnf update --enable-repo=updates-testing mutter
> ```

Unfortunately this did not fix it for me (latest nightly, fedora 43, nvidia, running with GBM_BACKEND=dri MESA_LOADER_DRIVER_OVERRIDE=zink )
I unplugged my second monitor, now it seems to be stable again.

**Comment by adiekwisch** [comment]
> I unplugged my second monitor, now it seems to be stable again.

That is interesting, as I also had the suspicion it is somehow related to multi-monitor. This is just anecdotal, but last time I tried it it worked on my second screen after previously repeatedly failing on my first.  

My screens have different refresh rates (240Hz on first vs 60Hz on second), maybe high refresh rates or difference in refresh rates is relevant.

**Comment by Epickitrolaz** [comment]
I too have different refresh rate screens. On the 165hz one the slicer freezes while on the 60hz one it works fine.

**Comment by jounathaen** [comment]
>  I unplugged my second monitor, now it seems to be stable again.

This also seems to fix it for me (deactivating in the system settings is sufficient), yet my monitors have the same refresh rate. 🤔

**Comment by haraldwer** [comment]
For me the issue occurs less frequently if all open windows (not just orca) are kept on the same monitor, even if multiple monitors are still connected.

**Comment by adiekwisch** [comment]
> > I unplugged my second monitor, now it seems to be stable again.
> 
> This also seems to fix it for me (deactivating in the system settings is sufficient), yet my monitors have the same refresh rate. 🤔

Have you tried leaving both screens active but moving it to the second one? I have now used Orca 10 times or more without problems by immediately upon start of Orca moving it to the second screen (using key combo to be fast, it moves before it renders any content). It is not ideal, but it is a workable solution for me until it is patched. 

Btw, is everybody having the problem on Fedora? 
I am on Fedora 43, Gnome 49 on Wayland, Mesa 25.2.7, Kernel 6.17.9-300.fc43.x86_64, and maybe also relevant: KDE is also intalled on my system.

**Comment by jounathaen** [comment]
> Have you tried leaving both screens active but moving it to the second one? I have now used Orca 10 times or more without problems by immediately upon start of Orca moving it to the second screen (using key combo to be fast, it moves before it renders any content). It is not ideal, but it is a workable solution for me until it is patched.

Lol, I can reproduce this 😅 

> Btw, is everybody having the problem on Fedora?
I am on Fedora 43, Gnome 49 on Wayland, Mesa 25.2.7, Kernel 6.17.9-300.fc43.x86_64, and maybe also relevant: KDE is also intalled on my system.

Yes, the same but without KDE.

Probably also relevant: The same issue occurs in Prusa Slicer as well.

**Comment by epoiate** [comment]
Tested with the latest Nightly Flatpak and the issue persists.

I'm also using Fedora 43 (silverblue with the latest patches), Nvidia, Single monitor

**Comment by jimothyr** [comment]
i found the solution on this related bug helped [https://github.com/OrcaSlicer/OrcaSlicer/issues/11276](https://github.com/OrcaSlicer/OrcaSlicer/issues/11276)   
`flatpak override --user --env=GBM_BACKEND=dri io.github.softfever.OrcaSlicer`

**Comment by Epickitrolaz** [comment]
> i found the solution on this related bug helped [#11276](https://github.com/OrcaSlicer/OrcaSlicer/issues/11276) `flatpak override --user --env=GBM_BACKEND=dri io.github.softfever.OrcaSlicer`

The fix doesn't work for me, tested on a full AMD system and on a laptop with an intel apu.

**Comment by marwndev** [comment]
> i found the solution on this related bug helped [#11276](https://github.com/OrcaSlicer/OrcaSlicer/issues/11276) `flatpak override --user --env=GBM_BACKEND=dri io.github.softfever.OrcaSlicer`

That worked for me. thanks!

**Comment by epoiate** [comment]
This also worked for me, but performance seem worse and a bit laggy.
At least it is working for now, thanks!

**Comment by wytr** [comment]
`flatpak override --user --env=GBM_BACKEND=dri io.github.softfever.OrcaSlicer`

Also worked for me, but performance in preview mode is really bad and ui still sometimes crashes / becomes unresponsive

``` 
OS: Fedora Linux 43 (Workstation Edition) x86_64
Kernel: Linux 6.17.12-300.fc43.x86_64
Uptime: 19 mins
Packages: 2431 (rpm), 41 (flatpak-system), 1 (flatpak-user)
Shell: bash 5.3.0
Display (GN03): 2560x1440 @ 165 Hz in 27" [External] *
Display (ROG PG278Q): 2560x1440 @ 144 Hz in 27" [External]
DE: GNOME 49.2
WM: Mutter (Wayland)
WM Theme: Adwaita
Theme: Adwaita [GTK2/3/4]
Icons: Adwaita [GTK2/3/4]
Font: Adwaita Sans (11pt) [GTK2/3/4]
Cursor: Adwaita (24px)
Terminal: Ptyxis 49.2
Terminal Font: Adwaita Mono (11pt)
CPU: AMD Ryzen 7 7800X3D (16) @ 5.05 GHz
GPU 1: NVIDIA GeForce RTX 3070 Lite Hash Rate [Discrete]
GPU 2: AMD Raphael [Integrated]
```

**Comment by brathering82** [comment]
Same for me with two displays and different refresh rates on EndeavourOS Gnome Wayland. 
I recently switched from Nvidia RTX3080 to AMD RX9070XT. It did not change a thing. So this is unrelated to the type of GPU.

BambuStudio behaves the same btw.

**Comment by flickerfly** [comment]
Fedora 43
ThinkPad X1 Carbon Gen 11
Intel Iris Xe Graphics (RPL-U)
Gnome 49
Wayland
2x Samsung 24" 59.95 Hz 2560x1440 monitors 125% scale
Builtin Monitor 60Hz 1920x1200 100% scale

I tried `GBM_BACKEND=dri orca` and didn't get good results. No change.

Then I enabled my built-in monitor and moved it to that screen as soon as it started. This did solve the rendering problem. I guess I'll do my slicing off the dock for now. :-(

**Comment by flickerfly** [comment]
I tested with the latest nightly including @mosfet80's GLFW lib update and that appears to have solved the problem. There are other issues, but I'm going to see if I can get away with that as it appears to also have improved support for my Elegoo Neptune 3 Pro. 

Thanks @mosfet80!

**Comment by epoiate** [comment]
The new nightly is working great! 
Thanks @mosfet80

**Comment by jounathaen** [comment]
~I just tried the latest nightly (flatpak, 2.3.2-dev ), but for me the issue persists :-/~

**Comment by jounathaen** [comment]
> I just tried the latest nightly (flatpak, 2.3.2-dev ), but for me the issue persists :-/

Ok, I was just stupid and didn't properly install the Flatpak. With rc2 it looks like it is working again. Thank you all for the work!
